### ISSUE TITLE
Reiherdamm und Hermann-Blohm-Straße VL 11

### ISSUE THREAD

**Issue by flecno** [breunigs/veloroute#16]
Hey, die Situation durch den Abriss des Radwegs wird noch schlimmer als angenommen.

In https://github.com/breunigs/veloroute/blob/master/blog/2019-04-03-11-reiherdamm-und-hermann-blohm-strasse.yaml wurde von einer Minimalbreite von 1,70m ausgegangen aber tatsächlich ist der Radstreifen an einigen Stellen nur 1,60m breit - trotz Schwerlastverkehr.

Da weitere Details zum Umbau nirgendwo zu finden waren habe ich nachgefragt: https://fragdenstaat.de/anfrage/planunterlagen-zu-hermann-blohm-strae-reiherdam-o-0975-18-o-eu/#nachricht-469518

Es gab sehr zügig eine Antwort mit den sehr umfangreichen Unterlagen. Besonders interessant ab Seite 398.

Ich habe das Dokument mal hier gesichert: https://github.com/flecno/veloroute11/raw/master/190212%20Vergabestellenversion_Vergabeunterlagen_Vergabe_O-0975-18-O-EU.pdf

Vielleicht findet ja jemand Zeit das in dem blog post zu beschreiben.

**Comment by breunigs** [comment]
Moin, danke für Deine Arbeit. Tatsächlich beruhen die 1,70m auf einer Fehlannahme meinerseits. Ich dachte da der Breitstrich zum Radweg gehört, darf man ihn mit dem Lenker überfahren. Das ist aber nicht so und die StVO und praktisch alle technischen Unterlagen diskriminieren systematisch indem diese 25cm immer zum Radweg gezählt werden, obwohl sie es nicht sind. Leider findet sich dieser Fehler auch in Veröffentlichungen für Bürger.

Schade das die 1,6m Abschnitte so lang sind. Wenn ich es richtig gesehen habe ist die ganze Blohmstraße so, bis auf ein Anfangsstück beim Elbtunnel. Auch spannend das Parkplätze höher bewertet werden als ordentliche Rad- und Fußwege, selbst im Bushaltestellenbereich an der Fähre.

Ich werde den Artikel demnächst aktualisieren.

**Comment by breunigs** [comment]
Artikel wurde aktualisiert: https://veloroute.hamburg/blog/2019-04-03-11-reiherdamm-und-hermann-blohm-strasse

**Comment by flecno** [comment]
Cool, danke!
