### ISSUE TITLE
Danke :-)

### ISSUE THREAD

**Issue by flobee** [breunigs/veloroute#26]
[veloroute.hamburg rocks](https://veloroute.hamburg) 

Danke! Das Video Material beispiellos! Wie ist das gemacht? Kennzeichen Filter etc. Das ist doch imens Aufwendig, oder?

**Comment by breunigs** [comment]
Moin,

freut mich, dass Dir die Seite gefällt. 

Zu den Videos: da steckt definitiv Aufwand drin, aber je nachdem was Du genau erreichen willst kommst Du recht schnell zu einem brauchbaren Ergebnis. Grob ist das:
- Aufnehmen: Action Kamera eines Markenherstellers mit extra Fischaugenlinse. Dann ist die dort eingebaute Bildstabilisierung und der Zeitraffer gut genug um nutzbare Videos zu bekommen, ohne diese Nachbearbeiten zu müssen. Leider muss man dafür noch tief in die Tasche greifen; die Technik ist erst seit 1-2 Jahren verfügbar und man bekommt wofür man bezahlt.
- Bilderkennung (Kennzeichen, Gesichter): das ist mit https://github.com/ultralytics/yolov5 gebaut. Das Projekt richtet sich an Entwickler oder Studis in diesem Bereich und ist einsteigerfreundlich. Lernkurve ist natürlich trotzdem da. Weil die mitgelieferten Modelle sich nicht für den Anwendungsfall eignen muss selbst eins trainiert werden. Das benötigt vergleichsweise teure Hardware ("dicke Gaming Grafikkarte"), lässt sich aber auch mieten. Die reine Erkennung kann dann auch auf schwächerer Hardware laufen, je nach Menge und Geduld 🙂. Es gibt in diesem Bereich keinen frei verfügbaren Corpus (=von Hand beschriftete Bilder), was auch heißt man muss selbst 10000+ Bilder beschriften. Zum Vergleich: die längeren Velorouten kommen auf etwa 20000 Bilder pro Richtung.
- Videoschnitt/zusammenfügen und Unkenntlichmachung: ffmpeg. Bei mir passiert das in einem Schritt, weil ich sonst die Zwischenschritte zwischenspeichern müsste, was entweder viel Speicherplatz braucht oder Qualitätseinbußen hat. Zum blurren verwende ich https://github.com/breunigs/frei0r-blur-from-json .
- alles verheiraten bzw. Automatisierung: den initialen Aufwand mal weggenommen, sind mittlerweile nur noch wenige Handgriffe notwendig um neue Videos hinzuzufügen. Das ist bei dem mehrstündigen Videomaterial auf der Seite auch notwendig. Nur durch die geringere Handarbeit konnte ich die Freizeitrouten ergänzen, was vorher an Aufwand/Freizeit/Motivation scheiterte.

Für den Heimanwendungszweck schau Dir mal https://github.com/tfaehse/DashcamCleaner an. Die dort mitgelieferten Modelle sind wie der Name schon vermuten lässt für den Anwendungsfall optimiert. Die Erkennungsqualität schwankt, was dem Stand der Technik und dem kleinen Corpus liegt. Prinzipiell gibt es auch Firmen die auf diese Probleme spezialisiert sind (z.B. https://understand.ai/), die aber allesamt zu teuer sind um für den Hobbybereich in Frage zu kommen.

**Comment by flobee** [comment]
Wow! Umfangreiche Antwort und Hinweise für das Detail!

 Danke sehr! 

Das ein oder andere merke ich mir mal oder schau ich mir an. Richtig: In diesem Fall Hobby Interesse :-)

Und um es auch noch zu hinterlassen: 
Bei den Chemnitzer Linux Tagen war ( die letzten male (vor corona)) immer ein ffmpeg Stand wo man Gesichtserkennung vorbei laufender Menschen zeigte. Im Grunde ist das ja die Realtime Antwort für Autoschilder.

Ne powerbank und ein Raspberry PI mit ffmpeg + Cam könnte das ja vielleicht schaffen und vielleicht LIVE Streams erzeugen. So ne idee da mir der Aufwand des 'Post Processings' schon klar war. Nur so ein Hinweis. Manchmal gibt es was, was die andere Szene vielleicht noch nicht weiss. Ist ja oft so. :)

Danke für die ganzen Infos! Phat! :-)
