### ISSUE TITLE
Gemeinsame Karte für Freizeit- und Alltagsrouten

### ISSUE THREAD

**Issue by Guacam-Ole** [breunigs/veloroute#27]
Wenn von A nach B fahren möchte in Hamburg versuche ich auszuwählen, welche Route denn am besten passt. Da wäre es sehr hilfreich wenn es eine gemeinsame Kartenansicht gibt für beide Arten von Routen. (Oder übersehe ich das Feature einfach irgendwo?)

**Comment by breunigs** [comment]
Ne, das gibt es tatsächlich nicht. Das ist auch nicht ganz einfach einzubauen aus zwei Gründen:
- die Routen-Icons in der Karte (z.B. orange ⓬ für Alltagsroute 12) werden nur angezeigt, wenn Routen sich nicht überlappen um Missverständnisse zu vermeiden. Diese "Kollisionserkennung" passiert innerhalb eines Routentyps, weil ich bei langen Überschneidungen (z.B. Alltagsroute 4 und Freizeitroute 1 an der Alster) sonst nie Icons einblenden könnte. Das ist bisher sehr simpel: einfach eine Ebene pro Icontyp im Kartendesigner, die dann auf der Seite jeweils ein/ausgeblendet werden. Sobald man "mehr als eine" als Option erlaubt, explodieren die Kombinationen – nur Alltag, nur Freizeit, nur RSW, All+Frei, All+RSW, Frei+RSW, alle. Das mit dem simplen Ansatz nicht mehr brauchbar zu bewerkstelligen, d.h. ich muss mir irgendwas schlaueres überlegen. Das Problem gibt's analog auch bei den Routen selbst.
- wie man das brauchbar in die Seite einbaut, ohne die Nutzer zu überfordern. Die Seite ist bereits jetzt schon komplex mit ihrer 3 Teilung in Karte/Video/Text. Auf mittleren Bildschirmen ("Tablet") ist die Seite noch benutzbar, aber auf dem Handy muss man schon sehr motiviert sein sie zu verwenden. Da jetzt noch irgendwo einen Button dranzupappen halte ich daher nicht für sinnvoll. Am ehesten irgendwo ein halb-verstecktes "Einstellungen" Menü, was aber doof ist wenn man auf einen Artikel klickt der dann die Ebenauswahl überschreibt. Da kommen dann auch Fragen auf wie "was passiert wenn man auf einen Freizeitrouten Artikel klickt, aber die Freizeitrouten abgewählt hat?"

Die einfachste Option "immer alles anzeigen" habe ich probiert, aber dann sieht man den Wald vor lauter Bäumen nicht mehr.

Momentan habe ich keine guten Ideen für die beiden Probleme, etwas halbgares einbauen werde ich aber auch nicht. Man hat ja Qualitätsansprüche 🙂

**Comment by breunigs** [comment]
Achso, die Alternative für Deinen Anwendungsfall ist die OpenCycleMap: https://www.opencyclemap.org/?zoom=12&lat=53.59389&lon=9.98708&layers=B0000

**Comment by breunigs** [comment]
Moin,

seit einer Weile gibt es auf hinreichend großen Geräten (fast alles außer Handys) auf der Karte unten links einen Knopf wo man die angezeigten Ebenen auswählen kann. Das sollte Deinen Wunsch abdecken.

Beim Aufrufen von Artikeln kann es sein, dass die Ansicht zurückgesetzt wird, damit sichergestellt ist dass alle relevanten Routen für den Artikel angezeigt werden.
